// AUTO-GENERATED CLIENTS INDEX - DO NOT EDIT
// This file exports all client functions from individual table client files
// Run schema/generators/generate-clients-from-edits.mts to regenerate

// Client for notifications
export * from './notifications';
// Client for photos
export * from './photos';
// Client for classes
export * from './classes';
// Client for children
export * from './children';
// Client for parent_child_relationships
export * from './parent_child_relationships';
// Client for class_assignments
export * from './class_assignments';
// Client for config_fields
export * from './config_fields';
// Client for daily_logs
export * from './daily_logs';
// Client for worksheets
export * from './worksheets';
// Client for users
export * from './users';
// Client for attendance
export * from './attendance';
// Client for milestones
export * from './milestones';
// Client for announcements
export * from './announcements';
// Client for events
export * from './events';
// Client for messages
export * from './messages';
// Client for message_threads
export * from './message_threads';
// Client for photo_albums
export * from './photo_albums';
// Client for student_progress
export * from './student_progress';
// Client for curriculum
export * from './curriculum';
// Client for photo_tags
export * from './photo_tags';
// Client for system_logs
export * from './system_logs';
// Client for attendance_records
export * from './attendance_records';
// Client for reports
export * from './reports';
// Client for curriculum_assignments
export * from './curriculum_assignments';
// Client for curriculum_items
export * from './curriculum_items';
// Client for time_slots
export * from './time_slots';
// Client for curriculum_templates
export * from './curriculum_templates';
// Client for curriculum_executions
export * from './curriculum_executions';
// Client for curriculum_imports
export * from './curriculum_imports';
